export const TAB_SCREENSHOT = 'TAB_SCREENSHOT';
export const TAB_ANIMATION = 'TAB_ANIMATION';
export const SCREENSHOT_DEFAULT_FILENAME = 'screenshot{N}.png';
export const ANIMATION_DEFAULT_FILENAME = 'animation{N}.webm'; 

export const TOGGLE_RECORDING = 'TOGGLE_RECORDING';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_SCREENSHOT_FILENAME = 'SET_SCREENSHOT_FILENAME';
export const SET_SCREENSHOT_INPUT_ERROR = 'SET_SCREENSHOT_INPUT_ERROR';
export const SET_ANIMATION_FILENAME = 'SET_ANIMATION_FILENAME';
export const SET_ANIMATION_INPUT_ERROR = 'SET_ANIMATION_INPUT_ERROR';

export const TAKE_SCREENSHOT_SHORTCUT = 'Shift+Alt+4'; 
export const RECORD_SHORTCUT = 'Shift+Alt+5'; 
export const STOP_SHORTCUT = 'Shift+Alt+6'; 

export const TAB_BUTTON_STYLE = {
    fontSize: 90
};